spring.application.name=estudos

# Config do datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/estudos_db
spring.datasource.username=estudos
spring.datasource.password=estudos123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Kafka
spring.kafka.bootstrap-servers=localhost:29093

spring.kafka.consumer.group-id=estudos-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Kafka Topic Config
kafka.topic.pedidos=pedidos-topic
kafka.topic.pedidos.partitions=3
kafka.topic.pedidos.replication-factor=1
app.kafka.topic.auto-create=false

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=estudos
spring.rabbitmq.password=estudos123

# Config do ThreadPool asynchronous
async.executor.core-pool-size=5
async.executor.max-pool-size=10
async.executor.queue-capacity=25

# Config Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Sao_Paulo

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.cache.type=redis

# JWT
jwt.secret=ZGV2LXNlZ3JlZG8tZGVzZW52b2x2aW1lbnRvLXNwcmluZy1ib290LTIwMjYtYXBpLWp3dA==
jwt.expiration=86400000

# Logging
logging.level.estudos.spring.avancado.estudos=DEBUG
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
